"use client";

/**
 * llms.txt 结构化生成与校验系统 — 主页面
 * ============================================================
 * MVP 版本：文本直接输入 → 实时生成 llms.txt → 合规校验报告
 * 后续可扩展：网页抓取、文件上传、API 路由、持久化存储等
 */

import { useCallback, useMemo, useState } from "react";

// ─────────────────────────────────────────────────────────────
// 类型定义
// ─────────────────────────────────────────────────────────────

/** 校验项状态：通过 / 警告 / 失败 */
type ValidationStatus = "pass" | "warning" | "fail";

/** 单条校验结果 */
interface ValidationItem {
  id: string;
  label: string;
  detail: string;
  status: ValidationStatus;
}

/** 左侧 Tab 标识 */
type InputTab = "text" | "scrape" | "upload";

/** 项目基础配置 */
interface ProjectConfig {
  projectName: string;
  projectDescription: string;
  baseUrl: string;
  author: string;
}

// ─────────────────────────────────────────────────────────────
// 常量与演示数据
// ─────────────────────────────────────────────────────────────

/** 系统版本号 */
const APP_VERSION = "v1.0.0 Pro";

/** llms.txt 建议文件大小上限（字节） */
const SIZE_LIMIT_BYTES = 100 * 1024;

/** 演示用原始文本，一键填充便于软著截图与功能演示 */
const DEMO_RAW_TEXT = `# 智能文档助手

> 面向企业知识库的大模型索引解决方案

## 核心能力

- 自动从 Markdown / HTML 文档中提取结构化摘要
- 生成符合 llms.txt 规范的标准索引文件
- 内置合规校验：文件大小、标题层级、Markdown 语法

## 快速开始

1. 在左侧输入原始文档内容
2. 填写项目名称与描述
3. 右侧实时预览生成的 llms.txt 并查看校验报告

## 相关链接

- [官方规范说明](https://llmstxt.org/): llms.txt 标准文档
- [API 参考](/docs/api): RESTful 接口说明
- [常见问题](/docs/faq): 使用与合规 FAQ`;

/** 默认项目配置 */
const DEFAULT_CONFIG: ProjectConfig = {
  projectName: "",
  projectDescription: "",
  baseUrl: "",
  author: "",
};

// ─────────────────────────────────────────────────────────────
// 工具函数：llms.txt 生成与校验
// ─────────────────────────────────────────────────────────────

/**
 * 根据原始文本与项目配置，生成标准 llms.txt 内容
 * 规范参考：https://llmstxt.org/
 */
function generateLlmsTxt(rawText: string, config: ProjectConfig): string {
  const title = config.projectName.trim() || "未命名项目";
  const description =
    config.projectDescription.trim() ||
    "本项目索引文件由 llms.txt 结构化生成与校验系统自动生成。";

  const metaLines: string[] = [];
  if (config.baseUrl.trim()) {
    metaLines.push(`- 站点根路径: ${config.baseUrl.trim()}`);
  }
  if (config.author.trim()) {
    metaLines.push(`- 维护者: ${config.author.trim()}`);
  }
  metaLines.push(`- 生成时间: ${new Date().toLocaleString("zh-CN")}`);

  return `# ${title}

> ${description}

## 元信息

${metaLines.join("\n")}

## 文档正文

${rawText.trim()}

---
*Generated by llms.txt 结构化生成与校验系统 ${APP_VERSION}*
`;
}

/**
 * 执行合规与结构校验，返回校验报告条目列表
 */
function runValidation(llmsContent: string): ValidationItem[] {
  const byteSize = new TextEncoder().encode(llmsContent).length;
  const lines = llmsContent.split("\n");

  const items: ValidationItem[] = [];

  // 1. 文件大小上限评估
  if (byteSize <= SIZE_LIMIT_BYTES * 0.5) {
    items.push({
      id: "size",
      label: "文件大小上限评估",
      detail: `当前 ${(byteSize / 1024).toFixed(1)} KB，远低于建议上限 ${SIZE_LIMIT_BYTES / 1024} KB，适合作为大模型索引文件。`,
      status: "pass",
    });
  } else if (byteSize <= SIZE_LIMIT_BYTES) {
    items.push({
      id: "size",
      label: "文件大小上限评估",
      detail: `当前 ${(byteSize / 1024).toFixed(1)} KB，接近建议上限 ${SIZE_LIMIT_BYTES / 1024} KB，建议精简非核心段落。`,
      status: "warning",
    });
  } else {
    items.push({
      id: "size",
      label: "文件大小上限评估",
      detail: `当前 ${(byteSize / 1024).toFixed(1)} KB，已超出建议上限 ${SIZE_LIMIT_BYTES / 1024} KB，可能影响大模型加载效率。`,
      status: "fail",
    });
  }

  // 2. 标题结构完整度校验
  const hasH1 = /^#\s+.+/m.test(llmsContent);
  const h2Count = (llmsContent.match(/^##\s+.+/gm) || []).length;
  const hasBlockquote = /^>\s+.+/m.test(llmsContent);

  if (hasH1 && h2Count >= 2 && hasBlockquote) {
    items.push({
      id: "heading",
      label: "标题结构完整度校验",
      detail: `检测到一级标题 1 个、二级标题 ${h2Count} 个及项目描述引用块，结构完整。`,
      status: "pass",
    });
  } else if (hasH1 && h2Count >= 1) {
    items.push({
      id: "heading",
      label: "标题结构完整度校验",
      detail: `已有一级标题，二级标题 ${h2Count} 个；建议补充项目描述（> 引用块）及更多章节。`,
      status: "warning",
    });
  } else {
    items.push({
      id: "heading",
      label: "标题结构完整度校验",
      detail: "缺少必需的一级标题（#）或章节结构不完整，请检查输入内容。",
      status: "fail",
    });
  }

  // 3. Markdown 语法规范检查
  const issues: string[] = [];

  // 未闭合的链接语法
  const unclosedLinks = (llmsContent.match(/\[[^\]]*\]\([^)]*$/gm) || []).length;
  if (unclosedLinks > 0) issues.push(`发现 ${unclosedLinks} 处未闭合链接`);

  // 连续空标题
  const emptyHeadings = (llmsContent.match(/^#{1,6}\s*$/gm) || []).length;
  if (emptyHeadings > 0) issues.push(`发现 ${emptyHeadings} 个空标题行`);

  // 混用 Tab 缩进（部分解析器不兼容）
  const hasTabs = lines.some((line) => line.startsWith("\t"));
  if (hasTabs) issues.push("检测到 Tab 缩进，建议改用空格");

  // 行尾多余空格
  const trailingSpaces = lines.filter((l) => / +$/.test(l)).length;
  if (trailingSpaces > 5) issues.push(`${trailingSpaces} 行存在行尾多余空格`);

  if (issues.length === 0) {
    items.push({
      id: "markdown",
      label: "Markdown 语法规范检查",
      detail: "未发现明显语法问题，链接、标题与段落格式符合常见 Markdown 规范。",
      status: "pass",
    });
  } else if (issues.length <= 2) {
    items.push({
      id: "markdown",
      label: "Markdown 语法规范检查",
      detail: issues.join("；") + "。",
      status: "warning",
    });
  } else {
    items.push({
      id: "markdown",
      label: "Markdown 语法规范检查",
      detail: issues.join("；") + "，建议修正后再发布。",
      status: "fail",
    });
  }

  return items;
}

/** 根据校验状态返回 Tailwind 样式类名 */
function statusStyles(status: ValidationStatus): string {
  switch (status) {
    case "pass":
      return "bg-emerald-50 text-emerald-700 ring-emerald-600/20";
    case "warning":
      return "bg-amber-50 text-amber-700 ring-amber-600/20";
    case "fail":
      return "bg-rose-50 text-rose-700 ring-rose-600/20";
  }
}

/** 校验状态中文标签 */
function statusLabel(status: ValidationStatus): string {
  switch (status) {
    case "pass":
      return "通过";
    case "warning":
      return "警告";
    case "fail":
      return "失败";
  }
}

// ─────────────────────────────────────────────────────────────
// 子组件（内联，便于单文件维护；后续可拆至 components/）
// ─────────────────────────────────────────────────────────────

/** 校验状态徽章 */
function StatusBadge({ status }: { status: ValidationStatus }) {
  return (
    <span
      className={`inline-flex shrink-0 items-center rounded-full px-2.5 py-0.5 text-xs font-medium ring-1 ring-inset ${statusStyles(status)}`}
    >
      {statusLabel(status)}
    </span>
  );
}

/** 右侧空状态引导 */
function EmptyStateGuide() {
  return (
    <div className="flex h-full min-h-[320px] flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-200 bg-slate-50/80 px-6 py-12 text-center">
      <div className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-100 text-2xl">
        📄
      </div>
      <h3 className="text-base font-semibold text-slate-800">
        等待输入内容
      </h3>
      <p className="mt-2 max-w-sm text-sm leading-relaxed text-slate-500">
        请在左侧输入原始文档文本，或点击「填充演示数据」快速体验生成与校验流程。
        输入后，此处将实时展示 llms.txt 预览及合规报告。
      </p>
      <ul className="mt-6 space-y-1.5 text-left text-xs text-slate-400">
        <li>• 支持 Markdown 格式原文</li>
        <li>• 自动补全项目元信息与标准结构</li>
        <li>• 实时校验文件大小、标题层级与语法规范</li>
      </ul>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 主页面组件
// ─────────────────────────────────────────────────────────────

export default function HomePage() {
  // ── 状态管理 ──
  const [activeTab, setActiveTab] = useState<InputTab>("text");
  const [rawText, setRawText] = useState("");
  const [config, setConfig] = useState<ProjectConfig>(DEFAULT_CONFIG);
  const [copySuccess, setCopySuccess] = useState(false);

  /** 是否有有效输入（用于控制右侧空状态） */
  const hasInput = rawText.trim().length > 0;

  /** 实时生成的 llms.txt 内容 */
  const llmsContent = useMemo(() => {
    if (!hasInput) return "";
    return generateLlmsTxt(rawText, config);
  }, [rawText, config, hasInput]);

  /** 实时校验报告 */
  const validationItems = useMemo(() => {
    if (!llmsContent) return [];
    return runValidation(llmsContent);
  }, [llmsContent]);

  // ── 事件处理 ──

  /** 清空输入区 */
  const handleClear = useCallback(() => {
    setRawText("");
    setConfig(DEFAULT_CONFIG);
  }, []);

  /** 填充演示数据 */
  const handleFillDemo = useCallback(() => {
    setRawText(DEMO_RAW_TEXT);
    setConfig({
      projectName: "智能文档助手",
      projectDescription:
        "面向企业知识库的大模型索引解决方案，支持自动化生成与合规校验。",
      baseUrl: "https://docs.example.com",
      author: "产品技术部",
    });
  }, []);

  /** 更新配置字段 */
  const updateConfig = useCallback(
    (field: keyof ProjectConfig, value: string) => {
      setConfig((prev) => ({ ...prev, [field]: value }));
    },
    [],
  );

  /** 一键复制 llms.txt */
  const handleCopy = useCallback(async () => {
    if (!llmsContent) return;
    try {
      await navigator.clipboard.writeText(llmsContent);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch {
      /* 降级：选区复制由浏览器处理，此处静默失败 */
    }
  }, [llmsContent]);

  /** 下载 .txt 文件 */
  const handleDownload = useCallback(() => {
    if (!llmsContent) return;
    const filename =
      (config.projectName.trim() || "llms").replace(/\s+/g, "-") + ".txt";
    const blob = new Blob([llmsContent], {
      type: "text/plain;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = filename;
    anchor.click();
    URL.revokeObjectURL(url);
  }, [llmsContent, config.projectName]);

  /** Tab 切换：三个 Tab 均可切换，非 MVP 功能展示占位提示 */
  const handleTabChange = useCallback((tab: InputTab) => {
    setActiveTab(tab);
  }, []);

  // ── Tab 配置 ──
  const tabs: { id: InputTab; label: string }[] = [
    { id: "text", label: "文本直接输入" },
    { id: "scrape", label: "网页抓取" },
    { id: "upload", label: "文件上传" },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30">
      {/* ═══════════════ 顶部导航栏 ═══════════════ */}
      <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur-md">
        <div className="mx-auto flex max-w-[1600px] flex-col gap-2 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-600 to-violet-600 text-sm font-bold text-white shadow-lg shadow-indigo-500/25">
              AI
            </div>
            <div>
              <div className="flex flex-wrap items-center gap-2">
                <h1 className="text-lg font-bold tracking-tight text-slate-900 sm:text-xl">
                  llms.txt 结构化生成与校验系统
                </h1>
                <span className="rounded-md bg-indigo-100 px-2 py-0.5 text-xs font-semibold text-indigo-700">
                  {APP_VERSION}
                </span>
              </div>
              <p className="mt-0.5 text-xs text-slate-500 sm:text-sm">
                符合大模型标准索引文件规范，适用于文档提炼与合规校验
              </p>
            </div>
          </div>
          <div className="hidden items-center gap-2 text-xs text-slate-400 sm:flex">
            <span className="h-2 w-2 rounded-full bg-emerald-500" />
            系统就绪
          </div>
        </div>
      </header>

      {/* ═══════════════ 主内容区：左右分栏 ═══════════════ */}
      <main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-2 lg:gap-8">
          {/* ────────── 左侧：输入与配置区 ────────── */}
          <section className="flex flex-col rounded-2xl border border-slate-200/80 bg-white shadow-sm shadow-slate-200/50">
            {/* Tab 导航 */}
            <div className="flex border-b border-slate-100">
              {tabs.map((tab) => (
                <button
                  key={tab.id}
                  type="button"
                  onClick={() => handleTabChange(tab.id)}
                  className={`relative flex-1 px-4 py-3.5 text-sm font-medium transition-colors ${
                    activeTab === tab.id
                      ? "text-indigo-600"
                      : "text-slate-500 hover:text-slate-700"
                  }`}
                >
                  {tab.label}
                  {activeTab === tab.id && (
                    <span className="absolute inset-x-4 -bottom-px h-0.5 rounded-full bg-indigo-600" />
                  )}
                </button>
              ))}
            </div>

            <div className="flex flex-1 flex-col p-5 sm:p-6">
              {/* 未开放 Tab：可切换样式 + 占位提示 */}
              {activeTab !== "text" && (
                <div className="flex flex-1 flex-col items-center justify-center rounded-xl border border-dashed border-slate-200 bg-slate-50/60 px-6 py-16 text-center">
                  <div className="mb-3 text-3xl opacity-60">
                    {activeTab === "scrape" ? "🌐" : "📁"}
                  </div>
                  <p className="text-sm font-medium text-slate-600">
                    {activeTab === "scrape" ? "网页抓取" : "文件上传"}
                  </p>
                  <p className="mt-2 text-xs text-slate-400">
                    将在后续版本开放
                  </p>
                </div>
              )}

              {activeTab === "text" && (
                <>
                  {/* 大文本输入框 */}
                  <div className="mb-5">
                    <div className="mb-2 flex items-center justify-between">
                      <label
                        htmlFor="raw-text"
                        className="text-sm font-medium text-slate-700"
                      >
                        原始文档内容
                      </label>
                      <div className="flex gap-2">
                        <button
                          type="button"
                          onClick={handleFillDemo}
                          className="rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-1.5 text-xs font-medium text-indigo-700 transition hover:bg-indigo-100"
                        >
                          填充演示数据
                        </button>
                        <button
                          type="button"
                          onClick={handleClear}
                          className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-600 transition hover:bg-slate-50"
                        >
                          清空
                        </button>
                      </div>
                    </div>
                    <textarea
                      id="raw-text"
                      value={rawText}
                      onChange={(e) => setRawText(e.target.value)}
                      placeholder="在此粘贴或输入 Markdown / 纯文本文档内容…"
                      rows={12}
                      className="w-full resize-y rounded-xl border border-slate-200 bg-slate-50/50 px-4 py-3 font-mono text-sm leading-relaxed text-slate-800 placeholder:text-slate-400 focus:border-indigo-400 focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                    />
                    <p className="mt-1.5 text-right text-xs text-slate-400">
                      {rawText.length} 字符
                    </p>
                  </div>

                  {/* 基础配置项 */}
                  <div className="space-y-4 border-t border-slate-100 pt-5">
                    <h2 className="text-sm font-semibold text-slate-800">
                      项目配置
                    </h2>
                    <div className="grid gap-4 sm:grid-cols-2">
                      <div className="sm:col-span-2">
                        <label
                          htmlFor="project-name"
                          className="mb-1 block text-xs font-medium text-slate-600"
                        >
                          项目名称
                        </label>
                        <input
                          id="project-name"
                          type="text"
                          value={config.projectName}
                          onChange={(e) =>
                            updateConfig("projectName", e.target.value)
                          }
                          placeholder="例如：智能文档助手"
                          className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                        />
                      </div>
                      <div className="sm:col-span-2">
                        <label
                          htmlFor="project-desc"
                          className="mb-1 block text-xs font-medium text-slate-600"
                        >
                          项目描述
                        </label>
                        <input
                          id="project-desc"
                          type="text"
                          value={config.projectDescription}
                          onChange={(e) =>
                            updateConfig("projectDescription", e.target.value)
                          }
                          placeholder="一句话概括项目用途"
                          className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                        />
                      </div>
                      <div>
                        <label
                          htmlFor="base-url"
                          className="mb-1 block text-xs font-medium text-slate-600"
                        >
                          站点根路径（可选）
                        </label>
                        <input
                          id="base-url"
                          type="url"
                          value={config.baseUrl}
                          onChange={(e) =>
                            updateConfig("baseUrl", e.target.value)
                          }
                          placeholder="https://docs.example.com"
                          className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                        />
                      </div>
                      <div>
                        <label
                          htmlFor="author"
                          className="mb-1 block text-xs font-medium text-slate-600"
                        >
                          维护者（可选）
                        </label>
                        <input
                          id="author"
                          type="text"
                          value={config.author}
                          onChange={(e) =>
                            updateConfig("author", e.target.value)
                          }
                          placeholder="团队或负责人"
                          className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
                        />
                      </div>
                    </div>
                  </div>
                </>
              )}
            </div>
          </section>

          {/* ────────── 右侧：生成与校验区 ────────── */}
          <section className="flex flex-col gap-6">
            {!hasInput ? (
              <EmptyStateGuide />
            ) : (
              <>
                {/* 上方：合规与结构校验报告 */}
                <div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm shadow-slate-200/50 sm:p-6">
                  <div className="mb-4 flex items-center justify-between">
                    <h2 className="text-sm font-semibold text-slate-800">
                      合规与结构校验报告
                    </h2>
                    <span className="text-xs text-slate-400">
                      实时更新
                    </span>
                  </div>
                  <ul className="space-y-3">
                    {validationItems.map((item) => (
                      <li
                        key={item.id}
                        className="flex gap-3 rounded-xl border border-slate-100 bg-slate-50/50 p-4"
                      >
                        <div className="min-w-0 flex-1">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="text-sm font-medium text-slate-800">
                              {item.label}
                            </span>
                            <StatusBadge status={item.status} />
                          </div>
                          <p className="mt-1.5 text-xs leading-relaxed text-slate-500">
                            {item.detail}
                          </p>
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* 下方：llms.txt 预览窗口 */}
                <div className="flex flex-1 flex-col rounded-2xl border border-slate-200/80 bg-white shadow-sm shadow-slate-200/50">
                  <div className="flex items-center justify-between border-b border-slate-100 px-5 py-3.5 sm:px-6">
                    <h2 className="text-sm font-semibold text-slate-800">
                      llms.txt 预览
                    </h2>
                    <span className="rounded bg-slate-100 px-2 py-0.5 font-mono text-xs text-slate-500">
                      {new TextEncoder().encode(llmsContent).length} bytes
                    </span>
                  </div>
                  <pre className="max-h-[360px] flex-1 overflow-auto bg-slate-900 px-5 py-4 font-mono text-xs leading-relaxed text-emerald-300/95 sm:px-6 sm:text-sm">
                    {llmsContent}
                  </pre>
                  <div className="flex flex-wrap gap-3 border-t border-slate-100 px-5 py-4 sm:px-6">
                    <button
                      type="button"
                      onClick={handleCopy}
                      className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm transition hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500/50"
                    >
                      {copySuccess ? "✓ 已复制" : "一键复制"}
                    </button>
                    <button
                      type="button"
                      onClick={handleDownload}
                      className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-300/50"
                    >
                      下载 .txt 文件
                    </button>
                  </div>
                </div>
              </>
            )}
          </section>
        </div>
      </main>

      {/* ═══════════════ 页脚 ═══════════════ */}
      <footer className="border-t border-slate-200/60 py-4 text-center text-xs text-slate-400">
        © {new Date().getFullYear()} llms.txt 结构化生成与校验系统 · 大模型标准索引文件自动化工具
      </footer>
    </div>
  );
}
